-- --------------------------------------------------------
-- INSERINDO REGISTROS REFERENCIA
-- --------------------------------------------------------

-- tipo_viagem
INSERT INTO tbl_tipo_viagem(nome)
VALUES
("Aventura"),
("Cultural"),
("Gastronômica"),
("Lazer"),
("Trabalho"),
("Estudo/Intercambio"),
("Voluntarioado"),
("Esportiva");

-- pais
INSERT INTO tbl_pais (nome) VALUES
('Afeganistão'),
('África do Sul'),
('Albânia'),
('Alemanha'),
('Andorra'),
('Angola'),
('Antígua e Barbuda'),
('Arábia Saudita'),
('Argélia'),
('Argentina'),
('Armênia'),
('Austrália'),
('Áustria'),
('Azerbaijão'),
('Bahamas'),
('Bangladesh'),
('Barbados'),
('Barein'),
('Belarus'),
('Bélgica'),
('Belize'),
('Benin'),
('Bolívia'),
('Bósnia e Herzegovina'),
('Botswana'),
('Brasil'),
('Brunei'),
('Bulgária'),
('Burkina Faso'),
('Burundi'),
('Butão'),
('Cabo Verde'),
('Camarões'),
('Camboja'),
('Canadá'),
('Catar'),
('Cazaquistão'),
('Chade'),
('Chile'),
('China'),
('Chipre'),
('Colômbia'),
('Comores'),
('Congo'),
('Coreia do Norte'),
('Coreia do Sul'),
('Costa do Marfim'),
('Costa Rica'),
('Croácia'),
('Cuba'),
('Dinamarca'),
('Djibouti'),
('Dominica'),
('Egito'),
('El Salvador'),
('Emirados Árabes Unidos'),
('Equador'),
('Eritreia'),
('Eslováquia'),
('Eslovênia'),
('Espanha'),
('Estados Unidos'),
('Estônia'),
('Eswatini'),
('Etiópia'),
('Fiji'),
('Filipinas'),
('Finlândia'),
('França'),
('Gabão'),
('Gâmbia'),
('Gana'),
('Geórgia'),
('Granada'),
('Grécia'),
('Guatemala'),
('Guiana'),
('Guiné'),
('Guiné-Bissau'),
('Guiné Equatorial'),
('Haiti'),
('Holanda'),
('Honduras'),
('Hungria'),
('Iêmen'),
('Ilhas Marshall'),
('Ilhas Salomão'),
('Índia'),
('Indonésia'),
('Irã'),
('Iraque'),
('Irlanda'),
('Islândia'),
('Israel'),
('Itália'),
('Jamaica'),
('Japão'),
('Jordânia'),
('Kiribati'),
('Kuait'),
('Laos'),
('Lesoto'),
('Letônia'),
('Líbano'),
('Libéria'),
('Líbia'),
('Liechtenstein'),
('Lituânia'),
('Luxemburgo'),
('Madagascar'),
('Malásia'),
('Malawi'),
('Maldivas'),
('Mali'),
('Malta'),
('Marrocos'),
('Maurício'),
('Mauritânia'),
('México'),
('Micronésia'),
('Moçambique'),
('Moldávia'),
('Mônaco'),
('Mongólia'),
('Montenegro'),
('Myanmar'),
('Namíbia'),
('Nauru'),
('Nepal'),
('Nicarágua'),
('Níger'),
('Nigéria'),
('Noruega'),
('Nova Zelândia'),
('Omã'),
('Panamá'),
('Papua-Nova Guiné'),
('Paquistão'),
('Paraguai'),
('Peru'),
('Polônia'),
('Portugal'),
('Quênia'),
('Quirguistão'),
('Reino Unido'),
('República Centro-Africana'),
('República Democrática do Congo'),
('República Dominicana'),
('Romênia'),
('Ruanda'),
('Rússia'),
('Samoa'),
('San Marino'),
('Santa Lúcia'),
('São Cristóvão e Neves'),
('São Tomé e Príncipe'),
('São Vicente e Granadinas'),
('Seicheles'),
('Senegal'),
('Serra Leoa'),
('Sérvia'),
('Singapura'),
('Síria'),
('Somália'),
('Sri Lanka'),
('Sudão'),
('Sudão do Sul'),
('Suécia'),
('Suíça'),
('Suriname'),
('Tailândia'),
('Taiwan'),
('Tajiquistão'),
('Tanzânia'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trindade e Tobago'),
('Tunísia'),
('Turcomenistão'),
('Turquia'),
('Tuvalu'),
('Ucrânia'),
('Uganda'),
('Uruguai'),
('Uzbequistão'),
('Vanuatu'),
('Vaticano'),
('Venezuela'),
('Vietnã'),
('Zâmbia'),
('Zimbábue');
