DELIMITER $$
CREATE PROCEDURE ListarPaises()
BEGIN
    SELECT * FROM tbl_pais;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE BuscarPaisId(
  IN pais_id INT
)
BEGIN
    SELECT * FROM tbl_pais WHERE id = pais_id;
END $$
DELIMITER ;